### ISSUE TITLE
Can't level up

### ISSUE THREAD

**Issue by Mimble** [OXOIndustries/Trials-in-Tainted-Space#723]
Hi, I'm playing in Chrome on a Mac. I levelled up once just fine, but now cannot take on more xp because the level up button is unclickable. If you give me any instructions I can probably offer more info, but I'm not remotely a techie, just like the game.

**Comment by Jacques00** [comment]
After leveling up, your character should find a place to sleep (like the ship), in order to use the level upgrade properly (the level-up button should be active if conditions are right). If you've reached the level cap (level 8, I think), you cannot upgrade any further until the cap is lifted later in development.

**Comment by Mimble** [comment]
Aha, my crap memory strikes again. Thanks for the help. :)
