### ISSUE TITLE
Combat Bugs (Fazian Content)

### ISSUE THREAD

**Issue by Jacques00** [OXOIndustries/Trials-in-Tainted-Space#758]
* Combat victory (at least for Ehstraffe fight in the Fazian Quest) does not end at last hit for some raisin.
* Might have something to do with winning multiple waves, yet in testing, there is only just 1 starting wave instead of the 4 outlined in the code. Beating that one wave (Ehstraffe and 3x red myr guards), will "complete" the battle, but only after using a special, like a class ability or running.
* If this issue is related to wave-handling in combat, I have yet to test this for other wave-based fights, so I am unsure if all wave fights are affected. Singular fights don't seem to be affected so far though.

**Comment by Gedan** [comment]
It's not actually waves, I just named it badly. It's basically looking for the number of rounds.This is literally the first instances of it being used.

**Comment by Jacques00** [comment]
Ah, okay--thanks for the clarification!

**Comment by Trogdor-the-Burninator** [comment]
Unlike other group fights, It seems none of the combat actions come from the extra soldiers, so there is no benefit to attacking them. They are literally just damage sponges. If you defeat Ehstraffe on your first turn (with a lucky Rapid Fire or something), or stunlock her with headbutts or concussive arrows, the other soldiers will just stand there doing nothing until you either defeat them or the number of rounds runs out, and no dialogue will play between Ehstraffe and Fazian.
Other issues:
The 'venom kiss' lust attack seems way too accurate for what it is; I often had three or four of those attacks landing on me per round, which was both weird and annoying (since that's like 30-40 lust dmg per turn) Further, the attack is not blocked by 'sealed' armor like the Atma Armor, like most such chemical/pheromone attacks are elsewhere in the game.

**Comment by Fenoxo** [comment]
That seems incred-awful.

**Comment by Jacques00** [comment]
Yea, Ehstraffe doesn't have any attacks of her own, so her combat A.I. is of the soldiers, with a note in the code scripts saying just that (Gedan was just being lazy!). I think a possible remedy is to either make it obvious that Ehstraffe needs to be defeated (by making more enemies spawn as the others fall), or actually give Estraffe some attacks to use and migrate the current A.I. to the troops. 

Another note is that the attacks are not split into melee/ranged attacks, but rather just damage applicators. I have no idea if this is also due to getting the attacks in quick, because Ehstraffe is the A.I., or because the combat is relatively in close-quarters, but just something I'd thought to bring up!

I do agree though, the lust attack might need to be either tuned down or have a less chance of being used--at the moment, all four attacks are equal in weight.

**Comment by Trogdor-the-Burninator** [comment]
> or actually give Estraffe some attacks to use and migrate the current A.I. to the troops. 
This is really the only option. There's no point to having multiple targets to hit if taking out the other targets or hitting them with status effects doesn't do anything. Might as well make it another one of those "multiple targets represented as one enemy" fights, like Tam-Tam or the rocket turrets.
The attacks being treated as damage applicators sounds like it's a big part of the reason why the lust attack seems so OP, if it's not taking reflexes into account. But yeah, right now, it feels like the reds are more interested in getting to first base than stopping you from uncovering their slave trade operation. :p

**Comment by Fenoxo** [comment]
Yeah, at a minimum, the attacks definitely need split up to the various mobs.

"plural" class fights confirmed for the superior way to not put much effort into a fight.

If Geddy doesn't get this in a couple days, I'll try and tackle it.
