### ISSUE TITLE
Minor typo in Renvra Double Trouble scene

### ISSUE THREAD

**Issue by mcgmcg** [OXOIndustries/Trials-in-Tainted-Space#846]
Currently playing on 0.6.59 (Public Release).

Renvra says “I hope you’re ready for that belly full of **get**,”.

I'm not sure what Renny-girl is meant to be saying here. It seems like a mistake in editing, where one sentence was changed to another but not every word from the original sentence was deleted.

There are a lot of errors in a similar vein in the "Buttslutinator" scenes (awful name by the way, I read the entire scene in Doofenshmirtz' voice. Scarred for life.), which is clearly unfinished and in the process of editing, which is what makes me think that happened in the Double Trouble scene.

Edit: to hit two typoes with one stone, in the scene where you return to your ship after retrieving the Myrellion probe, Shade states that... “Uveto VII. I’ve got a house there, a little place **is** Irestead I managed to buy." I'm sure she's not wealthy enough to have purchased the ENTIRETY of Irestead, right?

**Comment by Fenoxo** [comment]
I'm fairly certain it's just an archaic form of slang for seed/semen/offspring. I couldn't find a decent reference with a quick google, but I know I've seen it used that way before, and not just in this scene Savin wrote. If nothing else, it could be written off as a local variance in Myrellion slang. it seems pretty clear what it means from context clues.

I'm not certain what errors in the buttslutinator you're talking about, though the Dr. Doofenschmirtz nod was definitely intentional. My idea of editing is typically to chunk it into the game and let typo reports sort it out, primarily because I'm a shitty editor and it slows my output even further.

I've fixed the Irestead typo "is" -> "in". Not sure what the other typo is that you mention at the opening of that paragraph.

**Comment by mcgmcg** [comment]
The other typo was the one from the Renvra scene, which is apparently not a typo at all.

I just re-read all three buttslutinator scenes and I can't find the errors. I was sure it had tons of bizarre typoes, but maybe I was just seeing things by 4:00 a.m. 

P.S. No matter how hard you try, nobody will ever Doofenschmirtz erotic. [scarring intensifies]

**Comment by Fenoxo** [comment]
Just wait till we add Pairy the Platypus-morph, a UGC secret agent.
