### ISSUE TITLE
Auto-Autofellatio  error

### ISSUE THREAD

**Issue by Rodon107** [OXOIndustries/Trials-in-Tainted-Space#910]
After gaining the Auto-Autofellatio perk, the 'old' fashioned method, it fails to show up in the list and doesn't seem to trigger.  Tried sleeping for weeks with no notification.

The new Auto-Autofellatio scene also references the treatment, even if you didn't get the treatment.

Additional suggetion, add the queen perk after x # of times.

**Comment by Fenoxo** [comment]
I hate to be that guy, but if it doesn't shop up in your perk list you DON'T have it.

**Comment by Jacques00** [comment]
I think I have this fixed in a pull request already (the perk getting part)--but I think it was primarily pending a "generic" version of autofellatio. The scene you are accessing is supposed to be blocked by the cum-cow prerequisite in the Masturbation list, but the current build doesn't have that yet.

**Comment by Rodon107** [comment]
Fenoxo, yeah if figured that, still it kept saying it was giving me the perk.  

Jacquess00, I thought that was potentially the issue, I tried the treatment and it did show up then.  Granted, that hypno-cock scene didn't show up even a few weeks of sleeping, but maybe I needed to walk around for a while instead of simply sleeping.

Thanks anyways, closing this out then.
