### ISSUE TITLE
[0.6.78 - Android] New cheat codes can't be input at V-KO

### ISSUE THREAD

**Issue by NeitherMeNorYou** [OXOIndustries/Trials-in-Tainted-Space#919]
As the title says, the new treatment cheat codes aren't recognized by V-KO on Mhen'ga, making it impossible to enter them without a physical keyboard.

**Comment by ds6** [comment]
use this keyboard as a workaround, which in addition to being better than stock in general imo and being super customizable, can be triggered via a notification for any app at any time:
https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard
didn't even know you could put them in at V-KO because of this.

**Comment by NeitherMeNorYou** [comment]
Huh, so it does. I do have that keyboard for a while now because I needed it for my remote applications, but I wasn't aware that it supported a notification to trigger it.
This will make a lot of things easier.

In any case, Fenoxo added the ability to use the normal cheatcodes with V-KO's custom input a while back, I believe around the end of 2015, so I figured I'd point it out here.
